# Discord Bot Configuration
discord:
  channel_id: null  # If null, will use channel_name instead
  channel_name: "ai-art"  # Only used if channel_id is null

# Generation Settings
generation:
  backend: "huggingface"  # Options: huggingface, flux
  seconds_per_variation: 60
  max_variations: 20
  reaction_merging: "append"  # Options: "append" (more X, more Y, more Z)

# Display Settings
display:
  prompt_visibility: "None"  # Options: "Full", "None"
  debug_output: false

# Meta Reactions Configuration
meta_reactions:
  all_done: "<:VeistAllDone:1376541849485054062>"
  keep_going: "<:VeistKeepGoing:1376541842371510341>"
  go_back: "<:VeistGoBack:1376541845655650384>"

# Advanced Settings
retry:
  max_attempts: 3
  delay_seconds: 10 